// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReRoExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ReRoPackageString = "cb3e379b-62b5-4117-aadf-4ec977e58247";
        public static Guid ReRoPackage = new Guid(ReRoPackageString);

        public const string ReRoPackageCmdSetString = "5677189e-c94b-413f-8e29-b6050ebc901f";
        public static Guid ReRoPackageCmdSet = new Guid(ReRoPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MainMenuGroup = 0x2000;
        public const int SubMenu = 0x1000;
        public const int HelpSubMenu = 0x1050;
        public const int SubMenuGroup = 0x2050;
        public const int HelpSubMenuGroup = 0x2100;
        public const int BuildMetadataDatabaseCommandId = 0x1151;
        public const int AboutShowCommandId = 0x12E7;
    }
}