// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReRoExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ReRo.Extension.AA1A4D6D-4A5E-4D89-A177-9F5BAA4AE36B";
        public const string Name = "Relational Roslyn Visual Studio Extension";
        public const string Description = @"Inspect your project's Roslyn metadata with SQL";
        public const string Language = "en-US";
        public const string Version = "1.5";
        public const string Author = "lsoft";
        public const string Tags = "Roslyn SQL";
        public const bool IsPreview = false;
    }
}
